### ISSUE TITLE
Windows 7 Crash on Start

### ISSUE THREAD

**Issue by Jonah-Horowitz** [toggl/toggldesktop#1484]
I've been using Toggl Desktop for a while now and it was working fine this morning. This afternoon however, it crashes when I try to start it up with the message "TogglDesktop has stopped working". Here's a screenshot of the error message, if it helps:
![2015-08-17 15_28_17-toggldesktop](https://cloud.githubusercontent.com/assets/5613222/9314084/b0550e12-44f4-11e5-9412-4f8b80f43ec7.png)

**Comment by amulware** [comment]
Thanks for letting us know about the problem!

Could you send us your log files to support@toggl.com? They may help us understand what is going on.
You can find the files here: C:\Users\<username>\AppData\Local\TogglDesktop\toggldesktop.log
Please include in the email that the log file is for me (Paul), to make sure I see it as soon as possible.

Please also let us know what version of Windows you are using.

Sorry about the inconvenience!

**Comment by Jonah-Horowitz** [comment]
After first encountering this problem I reinstalled Toggl Desktop in the hopes that this would help, but it didn't. Now, however, I'm thinking that was a bad idea since there are no log files in that folder.
I'm using an up to date version of Windows 7.

**Comment by jamesthornton78** [comment]
Hi, I am having the same problem but on Windows 10, for the last couple of days - I'm not sure what started it. I have tried completely reinstalling and have checked the log files but neither show anything since the last successful launch (19th of August). I suppose there must a problem with permissions or the process is crashing before it initializes the logging code?

Any help would be much appreciated :smile: 
- James

**Comment by amulware** [comment]
Could you guys try starting Toggl Desktop from a command prompt and see if you get any error messages or other information that way, that is not included in the log files?

**Comment by Jonah-Horowitz** [comment]
Sure, here:
```Unhandled Exception: System.Configuration.ConfigurationErrorsException: Configur
ation system failed to initialize ---> System.Configuration.ConfigurationErrorsE
xception: Root element is missing. (C:\Users\JHorowitz\AppData\Local\Toggl\Toggl
Desktop.exe_Url_nmykuwnaiwey5jctue0o2u4gqyvvdoqq\7.2.281.0\user.config) ---> Sys
tem.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean rea
dToFirstElement, ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignor
eLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(Configurat
ionSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object send
er, InternalConfigEventArgs e)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sect
ionName)
   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   at System.Net.WebRequest.get_InternalDefaultWebProxy()
   at System.Net.WebRequest.get_DefaultWebProxy()
   at Bugsnag.Notifier..cctor()```

**Comment by amulware** [comment]
Thanks!

It might be that the programs settings file is corrupt. Deleting the directory `C:\Users\<username>\AppData\Local\Toggl` might fix this (the program will re-create the files).

Can you check if that does the trick?

**Comment by jamesthornton78** [comment]
Great, that seems to have fixed it! Thanks for the quick replies

**Comment by Jonah-Horowitz** [comment]
It has indeed fixed it, thank you!

**Comment by amulware** [comment]
Great to hear, and thanks for your patience!
