### ISSUE TITLE
Toggl Desktop beta channel automatic update from 7.3.318 to 7.3.325 on Windows 10 does not work

### ISSUE THREAD

**Issue by cori** [toggl/toggldesktop#1949]
I'm on Windows 10 Pro Version 1511 Build 10586.494, not running any Insiders build. 64-bit i7 @ 2.30 GHz w/ 16GB RAM.

![image](https://cloud.githubusercontent.com/assets/46317/16886192/5d6671aa-4a98-11e6-9229-9c0fa24d0b7a.png)

I see the above window when I look at About. When I click on restart the window closes, I get a little flash of what looks like Toggl retrieving and executing an update (it goes pretty quick, so hard to say exactly) and then Toggl opens up again but immediately displays the "stopped working" window ending up at this:
![image](https://cloud.githubusercontent.com/assets/46317/16886238/9bebd230-4a98-11e6-86fc-56550dc2d291.png)

When I click Close Program it runs through the same cycle again, and when I click Close Program again it quits. When I reopen it opens fine, but at 7.3.318.

Windows Application event log collects some combination of the following errors each time (which ones are collected vary a little):
<snip1> (Error)
Application: TogglDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 7409DAE8
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at TogglDesktop.Toggl+<>c__DisplayClass36.<createUpdateAction>b__35()
   at TogglDesktop.Toggl.RestartAndUpdate()
   at TogglDesktop.AboutWindow.onRestartButtonClick(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at TogglDesktop.Program.Main()
</snip1>
<snip2> (Error)
Faulting application name: TogglDesktop.exe, version: 7.3.318.0, time stamp: 0x573043d9
Faulting module name: KERNELBASE.dll, version: 10.0.10586.494, time stamp: 0x5775e78b
Exception code: 0xc0020001
Fault offset: 0x000bdae8
Faulting process id: 0x24ac
Faulting application start time: 0x01d1decdff23f7c0
Faulting application path: C:\Users\cori.schlegel\AppData\Local\TogglDesktop\TogglDesktop.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: 89817fe7-14b6-4c87-b774-263275c52af4
Faulting package full name: 
Faulting package-relative application ID: 
</snip2>
<snip3> (Information)
Fault bucket 108279956071, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: TogglDesktop.exe
P2: 7.3.318.0
P3: 573043d9
P4: KERNELBASE.dll
P5: 10.0.10586.494
P6: 5775e78b
P7: c0020001
P8: 000bdae8
P9: 
P10: 

Attached files:
C:\Users\cori.schlegel\AppData\Local\Temp\WER1DB6.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_TogglDesktop.exe_2d3d32c4b6ae5c89dda66c6a95ab198c690e1c7_18650c16_3fc66569

Analysis symbol: 
Rechecking for solution: 0
Report Id: 89817fe7-14b6-4c87-b774-263275c52af4
Report Status: 0
Hashed bucket: 675217b02e50638ec0fe1d7452c7fd3a
</snip3>

**Comment by cori** [comment]
I'll wait to pull the pre-release exe in case some additional troubleshooting is necessary.

**Comment by IndrekV** [comment]
I tried to replicate but without success. I would suggest manually clearing local files as it seems that the update could have corrupted local database. If there's something that has not synced to web then please create backup of local files before removing them.
Here's an article on how to clear local files: https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/#manual

**Comment by cori** [comment]
Yep, that did it. Thanks!
