### ISSUE TITLE
Windows app fails to start after a day of usage.

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2021]
User reports it happening after multiple reinstalls of the application.

More details in : 366857

Error stack:

```
System.Windows.Markup.XamlParseException:
The invocation of the constructor on type <TogglDesktop.MainWindow> 
that matches the specified binding constraints threw an exception. 
---> System.InvalidOperationException: TogglSettingsView expected=96 actual=88
at TogglDesktop.Toggl.StartUI(String version, IEnumerable`1 experimentIds)
at TogglDesktop.MainWindow.finalInitialisation()
```

**Comment by IndrekV** [comment]
Closing as issue is out of date and has not been reported recently.
