### ISSUE TITLE
Fix Xaml errors in windows.

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#2039]
```
System.Windows.Media.Animation Warning: 6 : 

Unable to perform action because the specified Storyboard 
was never applied to this object for interactive control.; 

Action='Stop'; 
Storyboard='System.Windows.Media.Animation.Storyboard';

Storyboard.HashCode='27806444'; 
Storyboard.Type='System.Windows.Media.Animation.Storyboard'; 
TargetElement='System.Windows.Media.Animation.Storyboard'; 
TargetElement.HashCode='27806444'; 
TargetElement.Type='System.Windows.Media.Animation.Storyboard'

---------------------

System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or 
FrameworkContentElement for target element. BindingExpression:Path=EntryBackColor; 
DataItem='TimeEntryCell' (Name=''); 
target element is 'SolidColorBrush' (HashCode=26530317); 
target property is 'Color' (type 'Color')

---------

System.Windows.Data Error: 4 : 
Cannot find source for binding with reference 
'ElementName=enableBreakPomodoroCheckBox'. 
BindingExpression:Path=IsChecked; 
DataItem=null; 
target element is 'TextBox' (Name='pomodoroBreakTimerDuration'); 
target property is 'IsEnabled' (type 'Boolean')

----------------

BindingExpression path error: 
'Colors' property not found on 'object' ''EditView' (Name='EditView')'. 
BindingExpression:Path=Colors; 
DataItem='EditView' (Name='EditView'); 
target element is 'ListBox' (Name='list');
 target property is 'ItemsSource' (type 'IEnumerable')

```

**Comment by skel35** [comment]
This is quite an old issue, so the errors changed.
Currently I was able to detect only two errors:
```
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.Brush' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: BrushConverter cannot convert from (null).

   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.BrushConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'

--------------------

Exception thrown: 'System.FormatException' in PresentationCore.dll
System.Windows.Data Error: 6 : 'TargetDefaultValueConverter' converter failed to convert value '' (type 'String'); fallback value will be used, if available. BindingExpression:Path=ProjectColor; DataItem='ListBoxItem' (HashCode=60491410); target element is 'Border' (Name=''); target property is 'Background' (type 'Brush') FormatException:'System.FormatException: Empty string not allowed.
   at MS.Internal.Parsers.ParseBrush(String brush, IFormatProvider formatProvider, ITypeDescriptorContext context)
   at System.Windows.Media.Brush.Parse(String value, ITypeDescriptorContext context)
   at System.Windows.Media.BrushConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.TargetDefaultValueConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
