### ISSUE TITLE
Windows App Crashing With Google Login

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2414]
CASE #660306

A user is having issues with the Toggl Desktop app for Windows when he tries to connect using the "Log In with Google" button. 

The app shows the following message: "Login failed. Are you online ?" - after which it crashes.

He's on Windows 10 Family edition on his desktop and laptop, but the issue is only showing on his laptop.

We've tried with firewalls, ports, antivirus, clearing local data (and deleting the entire Toggl desktop file), trying from a different network and re-installing the app - nothing worked. 

Attaching the ".log" file we obtained from the user. 

What finally worked (in terms of the user being able to log in without a crash) was resetting the password and logging in "manually" instead of logging in with Google. 

[toggldesktop.log](https://github.com/toggl/toggldesktop/files/1833096/toggldesktop.log)

**Comment by IndrekV** [comment]
Error message show is:

```
Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_token", Description:"", Uri:""

   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)

   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

   at Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at Google.Apis.Auth.OAuth2.UserCredential.<RevokeTokenAsync>d__c.MoveNext() in c:\code\google.com\google-api-dotnet-client\default\Tools\Google.Apis.Release\bin\Debug\test\default\Src\GoogleApis.Auth\OAuth2\UserCredential.cs:line 181

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at TogglDesktop.LoginView.<googleLogin>d__b.MoveNext() in c:\toggldesktop\src\ui\windows\TogglDesktop\TogglDesktop\ui\views\LoginView.xaml.cs:line 214

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.Run()

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at System.Windows.Application.Run(Window window)

   at System.Windows.Application.Run()

   at TogglDesktop.Program.Main() in c:\toggldesktop\src\ui\windows\TogglDesktop\TogglDesktop\Program.cs:line 104
```

**Comment by thasmarinho** [comment]
I had that problem right now and something really strange was the url. After click on "Log In with Google" button, select my account, the url appoints to a localhost address and crash completely.

Mentioned URL: 
http://localhost:52295/authorize/?code=4/AADPtOR4Y4gOtTGZ9PAQyepkRF6xHYpGibR_cJgpspeP78WOFrkM_uJHlYPN-xqx_reQa7YW3YXo4cb6Em8eCFg#

**Comment by bryanph** [comment]
Getting another user reporting the same error as mentioned by @thasmarinho: 19670733829

**Comment by NghiaTranUIT** [comment]
Unfortunately, I couldn't reproduce this issue in TogglDesktop 7.4.252 (Windows) with following scenarios:
- Login with Google with new google account (hasn't signed-in to Toggl.com)
- Login with Goggle with old google account (has already signed-in to Toggl.com)
- Comment logic and force call `attemptOfflineLogin` in order to see "Login failed. Are you online ?" (I assume that there was a bug when handling error from Google)
https://github.com/toggl/toggldesktop/blob/9baea61285b81a4a9343a6599a7c484cc9fda698/src/context.cc#L2238

In three scenarios, the app still worked and there are no crashes occurred.

On the other hand, the crash log show `Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_token"`, which occurred internally. I suppose that this out-of-date library could be responsible for this crash 💥 

## Additions
- TogglDesktop Windows is using `Google.Apis.Auth` with version 1.9.1
https://github.com/toggl/toggldesktop/blob/9baea61285b81a4a9343a6599a7c484cc9fda698/src/ui/windows/TogglDesktop/TogglDesktop/packages.config#L5 
- 1.9.1 Google.Apis.Auth is pretty out of date, which was released from 25th Dec 2014
https://github.com/googleapis/google-api-dotnet-client/releases/tag/1.9.1

**Comment by NghiaTranUIT** [comment]
To summarize, I would like to attempt to upgrading our Google.Apis.Auth to latest version, which is [v1.37.0](https://github.com/googleapis/google-api-dotnet-client/releases/tag/v1.37.0) in 10th Jan 2019 🚧
